fn main() {
    // The window loads the REMOTE origin https://chroneli.com, and in Tauri 2 a
    // command invoked from a remote origin has to resolve an explicit ACL entry.
    // `core:default` grants the CORE plugins only — it never grants an app
    // command — so with a bare `tauri_build::build()` there is no
    // `allow-timer-state` permission anywhere in the ACL and every
    // `invoke("timer_state", …)` from the page is rejected. The Rust still
    // compiles and the unit tests still pass, because none of it crosses IPC.
    //
    // Declaring the command here autogenerates `allow-timer-state` /
    // `deny-timer-state` under the `__app-acl__` key, which
    // `capabilities/default.json` then grants.
    //
    // NOTE: an app manifest also flips tauri's `has_app_acl_manifest` on, which
    // starts gating LOCAL origins too. The capability covers both — it sets no
    // `local: false` — so this does not trade one broken path for another.
    //
    // EVERY app command belongs in this list. A command that is only in
    // `tauri::generate_handler!` compiles, passes every unit test, and is
    // rejected at runtime with nothing the page can observe — that is exactly
    // how `timer_state` shipped inert for a whole branch. So there is one
    // `the_acl_lets_chroneli_com_*` test per entry here, and they are the only
    // thing in the crate that would notice.
    //
    // Two things about HOW this list takes effect, both surprising:
    //
    //   - It writes `permissions/autogenerated/<command>.toml` into the source
    //     tree — not into OUT_DIR — and then globs that whole directory. Those
    //     files are committed (see `permissions/autogenerated/timer_state.toml`)
    //     and a REMOVED command keeps working until its stale `.toml` is deleted
    //     too. Deleting an entry here means deleting its file in the same
    //     commit, or the ACL silently keeps granting it.
    //   - Because `capabilities/default.json` names each permission explicitly,
    //     forgetting this list while remembering the capability is a hard build
    //     failure ("Permission allow-… not found"), not silence. The silent case
    //     is forgetting BOTH, which is the one the tests above cover.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&["timer_state", "begin_browser_login"]),
        ),
    )
    .expect("failed to run tauri-build");
}
