/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as DesktopCallbackRouteImport } from './routes/desktop-callback'
import { Route as DesktopLoginRouteImport } from './routes/desktop-login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedInvoicesRouteImport } from './routes/_authed/invoices'
import { Route as AuthedProjectsRouteImport } from './routes/_authed/projects'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTimerRouteImport } from './routes/_authed/timer'
import { Route as AuthedInvoicesInvoiceIdRouteImport } from './routes/_authed/invoices_.$invoiceId'
import { Route as AuthedInvoicesNewRouteImport } from './routes/_authed/invoices_.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopCallbackRoute = DesktopCallbackRouteImport.update({
  id: '/desktop-callback',
  path: '/desktop-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopLoginRoute = DesktopLoginRouteImport.update({
  id: '/desktop-login',
  path: '/desktop-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInvoicesRoute = AuthedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimerRoute = AuthedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesInvoiceIdRoute = AuthedInvoicesInvoiceIdRouteImport.update({
  id: '/invoices_/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesNewRoute = AuthedInvoicesNewRouteImport.update({
  id: '/invoices_/new',
  path: '/invoices/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desktop-callback': typeof DesktopCallbackRoute
  '/desktop-login': typeof DesktopLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/projects': typeof AuthedProjectsRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/timer': typeof AuthedTimerRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desktop-callback': typeof DesktopCallbackRoute
  '/desktop-login': typeof DesktopLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/projects': typeof AuthedProjectsRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/timer': typeof AuthedTimerRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/desktop-callback': typeof DesktopCallbackRoute
  '/desktop-login': typeof DesktopLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/projects': typeof AuthedProjectsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/timer': typeof AuthedTimerRoute
  '/_authed/invoices_/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/_authed/invoices_/new': typeof AuthedInvoicesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desktop-callback'
    | '/desktop-login'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/invoices'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/timer'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desktop-callback'
    | '/desktop-login'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/invoices'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/timer'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/desktop-callback'
    | '/desktop-login'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authed/invoices'
    | '/_authed/projects'
    | '/_authed/reports'
    | '/_authed/settings'
    | '/_authed/timer'
    | '/_authed/invoices_/$invoiceId'
    | '/_authed/invoices_/new'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DesktopCallbackRoute: typeof DesktopCallbackRoute
  DesktopLoginRoute: typeof DesktopLoginRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-callback': {
      id: '/desktop-callback'
      path: '/desktop-callback'
      fullPath: '/desktop-callback'
      preLoaderRoute: typeof DesktopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-login': {
      id: '/desktop-login'
      path: '/desktop-login'
      fullPath: '/desktop-login'
      preLoaderRoute: typeof DesktopLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timer': {
      id: '/_authed/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthedTimerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices_/$invoiceId': {
      id: '/_authed/invoices_/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices_/new': {
      id: '/_authed/invoices_/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthedInvoicesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedProjectsRoute: typeof AuthedProjectsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTimerRoute: typeof AuthedTimerRoute
  AuthedInvoicesInvoiceIdRoute: typeof AuthedInvoicesInvoiceIdRoute
  AuthedInvoicesNewRoute: typeof AuthedInvoicesNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedProjectsRoute: AuthedProjectsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTimerRoute: AuthedTimerRoute,
  AuthedInvoicesInvoiceIdRoute: AuthedInvoicesInvoiceIdRoute,
  AuthedInvoicesNewRoute: AuthedInvoicesNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DesktopCallbackRoute: DesktopCallbackRoute,
  DesktopLoginRoute: DesktopLoginRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
